name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24"

      - name: Unit tests
        run: |
          make test
