name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b

      - name: Unit tests
        run: just test
