name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6

      - name: Unit tests
        run: just test
